# Generated by Django 5.2.4 on 2025-09-12 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0003_project_cover_image_url_project_latitude_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.BigIntegerField(help_text='Whole credits purchased (not lowest units)')),
                ('price_per_credit', models.DecimalField(decimal_places=2, help_text='Fiat price for UI/reference', max_digits=12)),
                ('tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(default='Completed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['buyer', '-created_at'], name='tokens_purc_buyer_i_5f8dbb_idx'), models.Index(fields=['project', '-created_at'], name='tokens_purc_project_8632cb_idx')],
            },
        ),
        migrations.CreateModel(
            name='TokenLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('MINT', 'Mint'), ('BURN', 'Burn'), ('TRANSFER', 'Transfer')], max_length=10)),
                ('amount', models.BigIntegerField(help_text='Token units in lowest denomination (wei-like)')),
                ('tx_hash', models.CharField(blank=True, default='', max_length=100)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_ledger', to='projects.project')),
            ],
            options={
                'indexes': [models.Index(fields=['project', '-created_at'], name='tokens_toke_project_f819c3_idx')],
            },
        ),
    ]
