# Generated by Django 5.2.4 on 2025-09-12 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tokens', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenledger',
            name='amount',
            field=models.DecimalField(decimal_places=0, help_text='Token units in lowest denomination (wei-like)', max_digits=78),
        ),
    ]
