# Generated by Django 5.2.4 on 2025-09-11 20:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_projects_pr_owner_i_4798b7_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cover_image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='project',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='location_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='onchain_project_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='total_credits_minted',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='project',
            index=models.Index(fields=['latitude', 'longitude'], name='projects_pr_latitud_7ac42e_idx'),
        ),
    ]
