runtime: python310
env: standard
entrypoint: sh -c "cd backend && python manage.py migrate --noinput && gunicorn -b :$PORT server.wsgi:application"

runtime_config:
  python_version: 3.10
  max_instances: 1
  env_vars:
    - GAE_ENV: standard

beta_settings:
  cloud_sql_instances: "carbon-490614:asia-south2:carbon-db=tcp:5432"

handlers:
  - url: /static
    static_dir: backend/staticfiles/
  - url: /media
    static_dir: backend/media/
  - url: /frontend
    static_dir: frontend/
  - url: /.*
    script: auto
