[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "server.settings"
python_files = ["tests.py", "test_*.py", "*_tests.py"]
addopts = "-ra -q --strict-markers --disable-warnings --maxfail=1 --cov=backend --cov-report=term-missing"
testpaths = ["backend/apps"]
